// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tank.domain;

import tank.domain.Base;

privileged aspect Base_Roo_JavaBean {
    
    public String Base.getBase() {
        return this.base;
    }
    
    public void Base.setBase(String base) {
        this.base = base;
    }
    
}
