// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tank.domain;

import tank.domain.KUYTOR;

privileged aspect KUYTOR_Roo_JavaBean {
    
    public String KUYTOR.getTOR() {
        return this.TOR;
    }
    
    public void KUYTOR.setTOR(String TOR) {
        this.TOR = TOR;
    }
    
}
