// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tank.domain;

import org.springframework.beans.factory.annotation.Configurable;
import tank.domain.KUYTOR;

privileged aspect KUYTOR_Roo_Configurable {
    
    declare @type: KUYTOR: @Configurable;
    
}
